name: SurfaceProArtist
favicon: null
layout_spectrum: 0.7951461002230644
typography_spectrum: 0.6785719126928598
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3213997462298721
  lightness: 0.039233301067724824
  saturation: 0.8760555519256741
  rhythmicContrast: 0.817176362266764
purpose: []
